const UsersActionTypes = {
    FETCH_USERS_START: "FETCH_USERS_START",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
    ADD_USER_START: "ADD_USER_START",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAILURE: "ADD_USER_FAILURE"
   

  };
  
  export default UsersActionTypes;
  